<?php
return [
    'nombre' => 'CENTRO DE DIAGNOSTICO CITOPATOLOGICO COCHABAMBA',
    'procedencia' => [
        'ADRIATICA',
        'AIQUILE',
        'ALIANZA',
        'ALIANZA VIDA',
        'APS MEDICAL GROUP SRL',
        'BANCA PRIVADA',
        'BELGA',
        'BISA'
    ],
    'tipo_analisis' => [
        'CITOLOGIA',
        'BIOPSIA',
        'INMUNOHISTOQUIMICA',
//        'BETHESDA',
        'HISTOPATOLOGICO'

    ],
    'extendido_compatible' => [
        'EPITELIO NORMAL',
        'CERVICITIS',
        'METAPLASIA ESCAMOSA',
        'COLPITIS',
        'ENDOCERVICITIS',
        'CARCINOMA ESC. INV.',
        'ECTOPIA',
        'QUERATOSIS',
        'ADENOCARCINOMA',
    ],
    'reac_inflamatoria' => [
        'AUSENTE',
        'LEVE',
        'VAGINA',
        'ENDOCERMIX',
        'MODERADA',
        'CERVIX',
        'OTROS',
        'ACENTUADA',
    ],
    'estudio_microbiologico' => [
        'BAC. DODERLAIN',
        'COCOS',
        'MONILIAS',
        'BAC. COCOIDES',
        'DIPLOCOCOS',
        'TRICOMONAS',
        'FLORA MIXTA',
        'VAGINOSIS BACTERIANA',
        'VIRUS',
        'COLIFORMES',
        'LEPTOTRIX VAG.',
        'OTROS',
    ],
    'convenios_id' => '10,13,23',
//    'convenios_id' => '10'
    'meses' => [
        'enero',
        'febrero',
        'marzo',
        'abril',
        'mayo',
        'junio',
        'julio',
        'agosto',
        'septiembre',
        'octubre',
        'noviembre',
        'diciembre'
    ],
    'meses-id' => [
        '01' => 'enero',
        '02' => 'febrero',
        '03' => 'marzo',
        '04' => 'abril',
        '05' => 'mayo',
        '06' => 'junio',
        '07' => 'julio',
        '08' => 'agosto',
        '09' => 'septiembre',
        '10' => 'octubre',
        '11' => 'noviembre',
        '12' => 'diciembre'
    ],
    'bethesda_calidad_muestra' => [
        '1' => 'Satisfactoria para evaluación',
        '2' => 'Satisfactoria para evaluación, parcialmente cubierta por 50% a 70% de inflamación',
        '3' => 'Satisfactoria para evaluación, parcialmente cubierta por 50% a 70% de hemorragia',
        '4' => 'Satisfactoria para evaluación, parcialmente cubierta por 50% a 70% de moco',
        '5' => 'Insatisfactoria para evaluación debido a celularidad escamosa insuficiente',
        '6' => 'Insatisfactoria para evaluación debido a que se encuentra cubierta en mas del 75% por inflamación',
        '7' => 'Insatisfactoria para evaluación debido a que se encuentra cubierta en mas del 75% por hemorragia',
        '8' => 'Insatisfactoria para evaluación debido a que se encuentra cubierta en mas del 75% por moco',
        '9' => 'Muestra rechazada o no procesada por falta de Identificación del portaobjetos',
        '10' => 'Muestra rechazada o no procesada ya que el portaobjetos se encuentra roto',
        '11' => 'Muestra rechazada o no procesada ya que los datos no coinciden con los del paciente',
    ],
    'bethesda_clasificacion_general' => [
        '1' => 'Negativo para Lesión Intraepitelial o Malignidad',
        '2' => 'Anomalías de Células Epiteliales',
        '3' => 'Otras Categorías',
    ],
    'bethesda_interpretacion' => [
        'N0' => 'Negativo para Lesión Intraepitelial o Malignidad',
        'N1' => 'Cambios celulares reactivos asociados a inflamación',
        'N2' => 'Cambios celulares reactivos asociados a radiación',
        'N3' => 'Cambios celulares reactivos asociados a dispositivo intrauterino (DIU)',
        'N4' => 'Cambios celulares reactivos asociados a atrofia',
        'O1' => 'Presencia de células endometriales en mujer mayor de 40 anos',
        'O2' => 'Células glandulares poshisterectomia',
        'E1' => 'Células escamosas atípicas de significado indeterminado (ASC-US)',
        'E2' => 'Células escamosas atípicas; no se puede descartar lesión intraepitelial de alto grado (ASC-H)',
        'E3' => 'Lesión intraepitelial de bajo grado (LIBG; incluye HPV/displasia leve/ NIC I)',
        'E4' => 'Lesión intraepitelial de alto grado (LIAG; incluye displasia moderada y grave/NIC II, NIC III/Carcinoma In Situ)',
        'E5' => 'Lesión intraepitelial de alto grado, con hallazgos sospechosos de invasión',
        'E6' => 'Carcinoma escamoso',
        'G1' => 'Células glandulares atípicas (AGC)',
        'G2' => 'Células glandulares atípicas sugestivas de neoplasia',
        'G3' => 'Células endocervicales atípicas sin especificar (NOS)',
        'G4' => 'Células endocervicales atípicas sugestivas de neoplasia',
        'G5' => 'Células endometriales atípicas sin especificar (NOS)',
        'G6' => 'Adenocarcinoma endocervical in situ',
        'G7' => 'Adenocarcinoma endocervical',
        'G8' => 'Adenocarcinoma endometrial',
        'G9' => 'Adenocarcinoma extrauterino',
        'G10' => 'Adenocarcinoma sin especificar (NOS)'
    ],
    'bethesta_checks' => [
        '1' => 'Bac. Doderlain',
        '2' => 'Bac. Cocoides',
        '3' => 'Flora Mixta',
        '4' => 'Coliformes',
        '5' => 'Cocos',
        '6' => 'Doplicocos',
        '7' => 'Gardnerella Vag.',
        '8' => 'Leptrotix Vag',
        '9' => 'Monilias',
        '10' => 'Tricomonas',
        '11' => 'Virus'
    ],
    'tecnica' => 'Fijación y obtención de secciones histológicas a partir del bloque de parafina en láminas silanizadas, sometidas a técnica de inmunoperoxidasa, recuperación antigénica con calor húmedo con tampón de recuperación universal. Detección a base de estreptavidina/biotina y revelados con sistema cromogénico DAB. Controles positivos internos y externos demuestran la fidelidad de las reacciones.',
    'marcadores' => [
        'ACTINA MUSCULO ESPECÍFICO - MSA (HHF35)',
        'ACTINA MUSCULO LISO - SMA (1A4)',
        'ANAPLASTIC LYMPHOMA KINASE - ALK (5A4)',
        'ALFA FETO PROTEINA',
        'ALFA-METHYLACYL-COA RACEMASE - AMARC (13H4): ',
        'AMILOIDE A (MC1)',
        'AMILOIDE P',
        'ANTIGENO PROSTÁTICO ESPECÍFICO - PSA (EP1588Y)',
        'ANDROGEN RECEPTOR (AR441)',
        'BCL-2 (100/D5)',
        'BCL-6 (P1F6)',
        'BER-EP4 (BER-EP4)',
        'B-CATENINA (14/BETA-CATENIN)',
        'BOB-1 (TG14)',
        'CA19-9 (BC/121SLE)',
        'CA-125 (OC125)',
        'CALPONINA (CALP)',
        'CALCITONINA',
        'CALRETININA',
        'CD1A (CD1A007)',
        'CD3 (E272)',
        'CD4 (BC/1F6)',
        'CD5 (SP19)',
        'CD7 (LP15)',
        'CD8 (SP16)',
        'CD10 (56C6)',
        'CD15 (MMA+BY87)',
        'CD19 (CD19)',
        'CD20 (L26)',
        'CD21 (2G9)',
        'CD23 (1B12)',
        'CD30 (CON6D/B5)',
        'CD31 (JC/70A)',
        'CD34 (QBEND/10)',
        'CD45 - ANTIGENO COMUN LEUCOCITARIO - LCA (PD7/26/16/2B11)',
        'CD45RO (UCHL-1)',
        'CD56 (BC56C04)',
        'CD57 (NK-1)',
        'CD68 (KP-1)',
        'CD79A (HM47/A9)',
        'CD99 (HO36-1.1)',
        'CD117 (Y145)',
        'CD138 (B-A38)',
        'CDX-2 (CDX2-88)',
        'CARCINOEMBRIONYC ANTIGEN - CEA',
        'C-ERBB-2/HER2 (EP1045Y)',
        'PANCITOQUERATINA (AE1/AE3)',
        'CITOQUERATINA 5/6 (CK5/6.007)',
        'CITOQUERATINA 7 (OV-TL 12/30)',
        'CITOQUERATINA 8/18 (5D3)',
        'CITOQUERATINA 19 (KS19.1)',
        'CITOQUERATINA 20 (KS20.8)',
        'CITOQUERATINA DE ALTO PESO MOLECULAR - CHMW (34BE12)',
        'CITOMEGALOVIRUS (DT10+BC90)',
        'CROMOGRANINA (LK2H10 + PHE5)',
        'COLAGENA IV (COL94)',
        'CICLINA D1 (EP12)',
        'DESMINA (D33)',
        'D2-40 (D2-40)',
        'DOG-1 (DOG1.1)',
        'EPIDERMAL GROWTH FACTOR RECEPTOR - EGFR (H11)',
        'EPSTEIN BAR VIRUS (EBV01, 02 AND 03)',
        'EPITHELIAL MEMBRANE ANTIGEN - EMA (E29)',
        'ERG (9FY)',
        'FACTOR VIII',
        'FACTOR XIIIA (E980.1)',
        'FOLLICLE STIMULATING HORMONE - FSH (FSH03)',
        'GCDFP-15 + MAMMAGLOBIN (D6 + 31A5)',
        'GLIAL FIBRILLARY ACID PROTEIN - GFAP',
        'GLYPICAN-3 (1G12)',
        'GLUT-1 (SPM498)',
        'GLUTAMINE SYNTHETASE (6GS)',
        'HEPATOCYTE SPECIFIC ANTIGEN (OCH1E5)',
        'HMB-45 (HMB-45)',
        'HPV (BPV-1/1H8 +CAMVIR)',
        'HUMAN CHORIONIC GONADOTROPIN - HCG',
        'INHIBINA (BC/R1)',
        'KAPPA (KDB-1)',
        'KI-67 (SP6)',
        'LAMBDA (LCN-2)',
        'MART-1 (M2-7C10+M2-9E3)',
        'MIOGENINA (MYG007)',
        'MOC-31 (MOC-31)',
        'MUC-4 (8G-7)',
        'MUC-5AC (45M1)',
        'MLH-1 (G168-15)',
        'MIELOPEROXIDASA - MPO',
        'MSH2 (FE11)',
        'MSH6 (BC/44)',
        'MUM-1 (BC5)',
        'NAPSIN-A (TMU-AD 02)',
        'NEUROFILAMENTOS (2F11)',
        'NEURONAL SPECIFIC ENOLASE - NSE (DT01 + BC100)',
        'OCT-2 (OCT-207)',
        'OCT-3/4 (SEMGC)',
        'P16INK4A (G175-405)',
        'PAX-5 (BC/24)',
        'PAX-8',
        'PLACENTAL ALKALINE PHOSPHATASE - PLAP (SP15)',
        'RECEPTORES DE ESTROGENO (6F11)',
        'RECEPTOR DE PROGESTERONA (SP2)',
        'P53 (DO-7)',
        'P63 (BC4A4)',
        'PTEN (6H2.1)',
        'PU-1 (G148-74)',
        'S100 (15E2E2)',
        'SALL4 (6E3)',
        'SINAPTOFISINA (27G12)',
        'TERMINAL DOXINUCLEOTIDIL TRANSFERASA - TdT',
        'TIROGLOBULINA (2H11+6E1)',
        'THYROID STIMULATING HORMONE - TSH (TSH01 + YSH02)',
        'TIA-1 (TIA-1)',
        'TTF-1 (8G7G3/1',
        'UROPLAKIN II + UROPLAKIN III (BC21 + BC17)',
        'VILLIN (1D2C3)',
        'WT-1 (BC.6F-H2)',
        'ZAP70 (BC.2F3.2)',


    ]
];